#!/bin/sh
# ---------------------------------------------------------------------------
# Startup script for pm2-gui on Synology DSM
# Auto-generated by pm2-gui Settings → Startup
# No per-user paths here — overrides go in .pm2-gui-boot.env
# Task Scheduler command: sh /path/to/pm2-gui/synology-start.sh
# ---------------------------------------------------------------------------

APP_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)

if [ -f "$APP_DIR/.pm2-gui-boot.env" ]; then
  # shellcheck disable=SC1091
  . "$APP_DIR/.pm2-gui-boot.env"
fi

if [ -n "${USER_HOME:-}" ]; then
  HOME="$USER_HOME"
elif [ -z "${HOME:-}" ] || [ "$HOME" = "/" ]; then
  _user=$(id -un 2>/dev/null || true)
  if [ -n "$_user" ] && [ -d "/var/services/homes/$_user" ]; then
    HOME="/var/services/homes/$_user"
  elif [ -n "$_user" ]; then
    HOME=$(getent passwd "$_user" 2>/dev/null | cut -d: -f6)
  fi
  unset _user
fi
export HOME

export PATH="${HOME:+$HOME/.npm-global/bin:}/usr/local/bin:/var/packages/Node.js_v20/target/usr/local/bin:/var/packages/Node.js_v18/target/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:${PATH:-}"

LOG="$APP_DIR/pm2-gui.log"
PORT="${PORT:-8088}"

{
  echo "=============================================================="
  echo "start-pm2-gui: launch attempt"
  echo "APP_DIR=$APP_DIR"
  echo "HOME=$HOME"
  echo "PATH=$PATH"

  cd "$APP_DIR" || { echo "ERROR: cannot cd to $APP_DIR"; exit 1; }

  NODE_BIN="$(command -v node || true)"
  if [ -z "$NODE_BIN" ]; then
    echo "ERROR: node not found on PATH"
    exit 1
  fi
  echo "using node: $NODE_BIN ($("$NODE_BIN" --version 2>/dev/null))"

  if command -v ss >/dev/null 2>&1; then
    if ss -ltn 2>/dev/null | grep -q ":${PORT} "; then
      echo "SKIP: port $PORT already in use — pm2-gui is already running"
      exit 0
    fi
  elif command -v netstat >/dev/null 2>&1; then
    if netstat -ltn 2>/dev/null | grep -q ":${PORT} "; then
      echo "SKIP: port $PORT already in use — pm2-gui is already running"
      exit 0
    fi
  fi

  if command -v pm2 >/dev/null 2>&1; then
    if pm2 describe pm2-gui >/dev/null 2>&1; then
      echo "WARN: removing pm2-gui from PM2 (dashboard must not be managed by PM2)"
      pm2 delete pm2-gui >/dev/null 2>&1 || true
      pm2 save >/dev/null 2>&1 || true
    fi
  fi

  echo "launching: node pm2-gui.js start"
  setsid "$NODE_BIN" pm2-gui.js start >> "$LOG" 2>&1 &
  echo "launched pid $! at $(date 2>/dev/null)"
} >> "$LOG" 2>&1
