'use strict'

var fs = require('fs')
var os = require('os')
var path = require('path')
var { execFile, execFileSync } = require('child_process')
var db = require('./db')

var TASK_NAME = 'pm2-gui boot'
var APP_ROOT = path.resolve(__dirname, '..')
var BOOT_ENV_FILE = '.pm2-gui-boot.env'
var DEFAULT_SYNO_APP_DIR = '/volume1/web/pm2-gui'
var DEFAULT_SYNO_HOME_PREFIX = '/var/services/homes'

function isSynology () {
  return fs.existsSync('/etc.defaults/VERSION') ||
    fs.existsSync('/usr/syno/bin/synowebapi') ||
    fs.existsSync('/usr/syno/bin/synoschedtask')
}

function isMacStylePath (value) {
  return /^\/Users\//.test(String(value || ''))
}

function which (bin) {
  try {
    return execFileSync('sh', ['-c', 'command -v ' + bin], { encoding: 'utf8' }).trim() || null
  } catch (err) {
    return null
  }
}

/**
 * Resolve display/config paths. Never bake a specific username into committed files —
 * prefer DB settings, then runtime detection.
 */
function getConfiguredPaths () {
  var username = os.userInfo().username
  var storedApp = ''
  var storedHome = ''
  try {
    storedApp = db.getSetting('startup_app_dir', '') || ''
    storedHome = db.getSetting('startup_user_home', '') || ''
  } catch (err) {}

  var appDir = storedApp || detectAppDir()
  var userHome = storedHome || detectUserHome(username)

  if (isSynology()) {
    if (!appDir || isMacStylePath(appDir) || appDir.indexOf('/volume') !== 0) {
      appDir = (APP_ROOT.indexOf('/volume') === 0) ? APP_ROOT : DEFAULT_SYNO_APP_DIR
    }
    if (!userHome || isMacStylePath(userHome)) {
      userHome = path.join(DEFAULT_SYNO_HOME_PREFIX, username)
    }
  }

  return {
    appDir: appDir,
    userHome: userHome,
    owner: username
  }
}

function detectAppDir () {
  if (isSynology() && APP_ROOT.indexOf('/volume') === 0) {
    return APP_ROOT
  }
  if (isSynology()) {
    return DEFAULT_SYNO_APP_DIR
  }
  return APP_ROOT
}

function detectUserHome (username) {
  username = username || os.userInfo().username
  if (isSynology()) {
    return path.join(DEFAULT_SYNO_HOME_PREFIX, username)
  }
  return process.env.HOME || os.homedir()
}

function getStartScriptPath () {
  return path.join(getConfiguredPaths().appDir, 'synology-start.sh')
}

function getPort () {
  try {
    var port = db.getSetting('port', null)
    if (port != null && port !== '') {
      return String(port)
    }
  } catch (err) {}
  return '8088'
}

/**
 * Portable boot script: resolves APP_DIR from its own location and USER_HOME
 * from .pm2-gui-boot.env or the Task Scheduler user. No hardcoded usernames.
 */
function buildStartScript () {
  return [
    '#!/bin/sh',
    '# ---------------------------------------------------------------------------',
    '# Startup script for pm2-gui on Synology DSM',
    '# Auto-generated by pm2-gui Settings → Startup',
    '# No per-user paths here — overrides go in .pm2-gui-boot.env',
    '# Task Scheduler command: sh /path/to/pm2-gui/synology-start.sh',
    '# ---------------------------------------------------------------------------',
    '',
    'APP_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)',
    '',
    'if [ -f "$APP_DIR/.pm2-gui-boot.env" ]; then',
    '  # shellcheck disable=SC1091',
    '  . "$APP_DIR/.pm2-gui-boot.env"',
    'fi',
    '',
    'if [ -n "${USER_HOME:-}" ]; then',
    '  HOME="$USER_HOME"',
    'elif [ -z "${HOME:-}" ] || [ "$HOME" = "/" ]; then',
    '  _user=$(id -un 2>/dev/null || true)',
    '  if [ -n "$_user" ] && [ -d "/var/services/homes/$_user" ]; then',
    '    HOME="/var/services/homes/$_user"',
    '  elif [ -n "$_user" ]; then',
    '    HOME=$(getent passwd "$_user" 2>/dev/null | cut -d: -f6)',
    '  fi',
    '  unset _user',
    'fi',
    'export HOME',
    '',
    'export PATH="${HOME:+$HOME/.npm-global/bin:}/usr/local/bin:/var/packages/Node.js_v20/target/usr/local/bin:/var/packages/Node.js_v18/target/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:${PATH:-}"',
    '',
    'LOG="$APP_DIR/pm2-gui.log"',
    'PORT="${PORT:-8088}"',
    '',
    '{',
    '  echo "=============================================================="',
    '  echo "start-pm2-gui: launch attempt"',
    '  echo "APP_DIR=$APP_DIR"',
    '  echo "HOME=$HOME"',
    '  echo "PATH=$PATH"',
    '',
    '  cd "$APP_DIR" || { echo "ERROR: cannot cd to $APP_DIR"; exit 1; }',
    '',
    '  NODE_BIN="$(command -v node || true)"',
    '  if [ -z "$NODE_BIN" ]; then',
    '    echo "ERROR: node not found on PATH"',
    '    exit 1',
    '  fi',
    '  echo "using node: $NODE_BIN ($("$NODE_BIN" --version 2>/dev/null))"',
    '',
    '  if command -v ss >/dev/null 2>&1; then',
    '    if ss -ltn 2>/dev/null | grep -q ":${PORT} "; then',
    '      echo "SKIP: port $PORT already in use — pm2-gui is already running"',
    '      exit 0',
    '    fi',
    '  elif command -v netstat >/dev/null 2>&1; then',
    '    if netstat -ltn 2>/dev/null | grep -q ":${PORT} "; then',
    '      echo "SKIP: port $PORT already in use — pm2-gui is already running"',
    '      exit 0',
    '    fi',
    '  fi',
    '',
    '  if command -v pm2 >/dev/null 2>&1; then',
    '    if pm2 describe pm2-gui >/dev/null 2>&1; then',
    '      echo "WARN: removing pm2-gui from PM2 (dashboard must not be managed by PM2)"',
    '      pm2 delete pm2-gui >/dev/null 2>&1 || true',
    '      pm2 save >/dev/null 2>&1 || true',
    '    fi',
    '  fi',
    '',
    '  echo "launching: node pm2-gui.js start"',
    '  setsid "$NODE_BIN" pm2-gui.js start >> "$LOG" 2>&1 &',
    '  echo "launched pid $! at $(date 2>/dev/null)"',
    '} >> "$LOG" 2>&1',
    ''
  ].join('\n')
}

function shellQuote (value) {
  return "'" + String(value).replace(/'/g, "'\\''") + "'"
}

function buildBootEnv (paths) {
  var lines = [
    '# Machine-local Synology boot overrides — generated by pm2-gui Settings → Startup',
    '# Do not commit this file. Values come from the SQLite settings DB.',
    'USER_HOME=' + shellQuote(paths.userHome),
    'PORT=' + shellQuote(getPort())
  ]
  // Only pin APP_DIR when it differs from "directory of synology-start.sh"
  // (unusual); detection via dirname is preferred.
  if (paths.appDir && paths.appDir !== APP_ROOT) {
    lines.push('APP_DIR=' + shellQuote(paths.appDir))
  }
  return lines.join('\n') + '\n'
}

/**
 * Write portable synology-start.sh + machine-local .pm2-gui-boot.env from DB/options.
 * The shell script never embeds usernames. Per-user values go in .pm2-gui-boot.env / DB.
 * Refuses to persist Mac /Users paths unless force=true.
 */
function ensureStartScript (options) {
  options = options || {}
  var paths = getConfiguredPaths()

  if (options.appDir) paths.appDir = String(options.appDir).trim()
  if (options.userHome) paths.userHome = String(options.userHome).trim()

  var hasMacPaths = isMacStylePath(paths.appDir) || isMacStylePath(paths.userHome)
  if (hasMacPaths && (options.appDir || options.userHome) && !options.force) {
    throw new Error(
      'Refusing to save Mac paths (' + paths.appDir + ' / ' + paths.userHome + '). ' +
      'Run Settings → Startup on the Synology, or set App dir / User home to ' +
      DEFAULT_SYNO_APP_DIR + ' and ' + DEFAULT_SYNO_HOME_PREFIX + '/YOUR_USERNAME'
    )
  }

  var persistLocal = !hasMacPaths || !!options.force
  if (persistLocal) {
    try {
      if (paths.appDir) db.setSetting('startup_app_dir', paths.appDir)
      if (paths.userHome) db.setSetting('startup_user_home', paths.userHome)
    } catch (err) {}
  }

  // Always refresh the portable script in this install; optionally mirror to configured dir.
  var targets = [APP_ROOT]
  if (persistLocal && paths.appDir && paths.appDir !== APP_ROOT && fs.existsSync(paths.appDir)) {
    targets.push(paths.appDir)
  }

  var scriptPath = null
  targets.forEach(function (dir) {
    var file = path.join(dir, 'synology-start.sh')
    fs.writeFileSync(file, buildStartScript(), { mode: 0o755 })
    try {
      fs.chmodSync(file, 0o755)
    } catch (err) {}

    if (persistLocal && paths.userHome) {
      fs.writeFileSync(path.join(dir, BOOT_ENV_FILE), buildBootEnv(paths), { mode: 0o600 })
    }

    scriptPath = file
  })

  var publicDir = (persistLocal && paths.appDir && !isMacStylePath(paths.appDir))
    ? paths.appDir
    : APP_ROOT
  return path.join(publicDir, 'synology-start.sh')
}

function getManualInstructions () {
  var paths = getConfiguredPaths()
  var scriptPath = path.join(paths.appDir, 'synology-start.sh')
  return {
    title: 'Manual Synology Task Scheduler setup',
    steps: [
      'Open Control Panel → Task Scheduler',
      'Create → Triggered Task → User-defined script',
      'Task name: ' + TASK_NAME,
      'User: ' + paths.owner + ' (same user that runs PM2 — not the disabled default admin)',
      'Event: Boot-up',
      'Enable: checked',
      'Task Settings → User-defined script:',
      'sh ' + scriptPath
    ],
    command: 'sh ' + scriptPath
  }
}

function listSchedulerTasks (fn) {
  var synowebapi = which('synowebapi') || '/usr/syno/bin/synowebapi'
  if (!fs.existsSync(synowebapi)) {
    return fn(new Error('synowebapi not found'))
  }

  execFile(synowebapi, [
    '--exec-fastwebapi',
    'api=SYNO.Core.TaskScheduler',
    'method=list',
    'version=3'
  ], { timeout: 15000 }, function (err, stdout) {
    if (err) {
      return fn(err)
    }
    try {
      var json = JSON.parse(stdout)
      if (!json.success) {
        return fn(new Error((json.error && json.error.code) ? 'TaskScheduler list failed: ' + json.error.code : 'TaskScheduler list failed'))
      }
      fn(null, (json.data && json.data.tasks) || [])
    } catch (parseErr) {
      fn(parseErr)
    }
  })
}

function findExistingTask (tasks) {
  return (tasks || []).find(function (task) {
    return task && task.name === TASK_NAME
  }) || null
}

function createViaSynowebapi (scriptPath, owner, fn) {
  var synowebapi = which('synowebapi') || '/usr/syno/bin/synowebapi'
  if (!fs.existsSync(synowebapi)) {
    return fn(new Error('synowebapi not found on this system'))
  }

  var schedule = JSON.stringify({
    date_type: 3,
    week_day: '0,1,2,3,4,5,6',
    hour: 0,
    minute: 0,
    repeat_hour: 0,
    repeat_min: 0,
    last_work_hour: 0
  })
  var script = 'sh ' + scriptPath

  execFile(synowebapi, [
    '--exec-fastwebapi',
    'api=SYNO.Core.TaskScheduler.Script',
    'method=Create',
    'version=2',
    'task_name=' + TASK_NAME,
    'script=' + script,
    'schedule=' + schedule,
    'enabled=true'
  ], { timeout: 20000 }, function (err, stdout, stderr) {
    if (!err) {
      try {
        var json = JSON.parse(stdout)
        if (json.success) {
          return fn(null, {
            method: 'synowebapi.Script.Create',
            taskId: json.data && (json.data.task_id || json.data.id),
            raw: json
          })
        }
      } catch (parseErr) {}
    }

    execFile(synowebapi, [
      '--exec-fastwebapi',
      'api=SYNO.Core.TaskScheduler',
      'method=create',
      'version=4',
      'name=' + TASK_NAME,
      'owner=' + owner,
      'enable=true',
      'type=script',
      'schedule=' + schedule,
      'extra=' + JSON.stringify({ script: script })
    ], { timeout: 20000 }, function (err2, stdout2) {
      if (err2) {
        return fn(new Error(
          'Could not create Task Scheduler entry automatically. ' +
          'DSM usually requires an administrator session for this API. ' +
          (stderr || err2.message || '')
        ))
      }
      try {
        var json2 = JSON.parse(stdout2)
        if (json2.success) {
          return fn(null, {
            method: 'synowebapi.TaskScheduler.create',
            taskId: json2.data && (json2.data.id || json2.data.task_id),
            raw: json2
          })
        }
        return fn(new Error('Task Scheduler create returned success=false'))
      } catch (parseErr2) {
        return fn(parseErr2)
      }
    })
  })
}

function installUserCrontab (scriptPath, fn) {
  var marker = '# pm2-gui-boot'
  var line = '@reboot /bin/sh ' + scriptPath + ' ' + marker

  execFile('crontab', ['-l'], { timeout: 5000 }, function (err, stdout) {
    var existing = (!err && stdout) ? stdout : ''
    if (existing.indexOf(marker) >= 0) {
      return fn(null, { method: 'crontab', status: 'already_installed' })
    }

    var next = existing.replace(/\s*$/, '')
    if (next) next += '\n'
    next += line + '\n'

    var child = execFile('crontab', ['-'], { timeout: 5000 }, function (err2) {
      if (err2) {
        return fn(err2)
      }
      fn(null, { method: 'crontab', status: 'installed' })
    })
    child.stdin.write(next)
    child.stdin.end()
  })
}

function getStatus (fn) {
  var synology = isSynology()
  var paths = getConfiguredPaths()
  var scriptPath = path.join(paths.appDir, 'synology-start.sh')
  var status = {
    synology: synology,
    platform: process.platform,
    appDir: paths.appDir,
    userHome: paths.userHome,
    owner: paths.owner,
    scriptPath: scriptPath,
    scriptExists: fs.existsSync(scriptPath),
    bootEnvPath: path.join(paths.appDir, BOOT_ENV_FILE),
    command: 'sh ' + scriptPath,
    taskName: TASK_NAME,
    canAutoCreate: synology && fs.existsSync('/usr/syno/bin/synowebapi'),
    existingTask: null,
    bootEnabled: !!db.getSetting('boot_task_enabled', false),
    lastMethod: db.getSetting('boot_task_method', ''),
    instructions: getManualInstructions(),
    warning: (!synology
      ? 'This machine is not Synology. Configure Startup on the NAS (values are stored in the DB / .pm2-gui-boot.env — never commit per-user paths).'
      : null)
  }

  if (!synology) {
    return fn(null, status)
  }

  listSchedulerTasks(function (err, tasks) {
    if (!err) {
      status.existingTask = findExistingTask(tasks)
    }
    fn(null, status)
  })
}

function setupBootTask (options, fn) {
  if (typeof options === 'function') {
    fn = options
    options = {}
  }
  options = options || {}

  var result = {
    methods: [],
    instructions: null
  }

  function finish (ok, method) {
    db.setSetting('boot_task_enabled', !!ok)
    if (method) db.setSetting('boot_task_method', method)
    result.ok = !!ok
    result.method = method || null
    result.instructions = getManualInstructions()
    fn(null, result)
  }

  var scriptPath
  try {
    scriptPath = ensureStartScript({
      appDir: options.appDir,
      userHome: options.userHome,
      force: !!options.force
    })
  } catch (err) {
    result.error = err.message
    result.instructions = getManualInstructions()
    return finish(false)
  }

  result.scriptPath = scriptPath
  result.command = 'sh ' + scriptPath
  var owner = getConfiguredPaths().owner

  if (!isSynology()) {
    result.note = 'Portable start script refreshed. Per-user paths belong in Settings → Startup on the NAS (written to .pm2-gui-boot.env).'
    result.instructions = getManualInstructions()
    return finish(true, 'script-only')
  }

  createViaSynowebapi(scriptPath, owner, function (err, info) {
    if (!err && info) {
      result.methods.push({ method: info.method, ok: true, info: info })
      return finish(true, info.method)
    }

    result.methods.push({
      method: 'synowebapi',
      ok: false,
      error: err ? err.message : 'unknown error'
    })

    installUserCrontab(scriptPath, function (cronErr, cronInfo) {
      if (cronErr) {
        result.methods.push({ method: 'crontab', ok: false, error: cronErr.message })
        result.error = (err && err.message) || cronErr.message
        result.note = 'Automatic Task Scheduler creation failed (often needs DSM admin privileges). Use the manual steps below.'
        return finish(false)
      }
      result.methods.push({ method: 'crontab', ok: true, info: cronInfo })
      result.note = 'DSM Task Scheduler API was unavailable, so a user crontab @reboot entry was installed instead.'
      finish(true, 'crontab')
    })
  })
}

module.exports = {
  TASK_NAME: TASK_NAME,
  BOOT_ENV_FILE: BOOT_ENV_FILE,
  isSynology: isSynology,
  getStatus: getStatus,
  setupBootTask: setupBootTask,
  ensureStartScript: ensureStartScript,
  getManualInstructions: getManualInstructions,
  getConfiguredPaths: getConfiguredPaths
}
