'use strict'

var fs = require('fs')
var os = require('os')
var path = require('path')
var { execFile, execFileSync } = require('child_process')
var db = require('./db')

var TASK_NAME = 'pm2-gui boot'
var APP_ROOT = path.resolve(__dirname, '..')

function isSynology () {
  return fs.existsSync('/etc.defaults/VERSION') ||
    fs.existsSync('/usr/syno/bin/synowebapi') ||
    fs.existsSync('/usr/syno/bin/synoschedtask')
}

function which (bin) {
  try {
    return execFileSync('sh', ['-c', 'command -v ' + bin], { encoding: 'utf8' }).trim() || null
  } catch (err) {
    return null
  }
}

function detectAppDir () {
  return APP_ROOT
}

function detectUserHome () {
  return process.env.HOME || os.homedir()
}

function getStartScriptPath () {
  return path.join(detectAppDir(), 'synology-start.sh')
}

function buildStartScript () {
  var appDir = detectAppDir()
  var userHome = detectUserHome()
  return [
    '#!/bin/sh',
    '# Auto-generated by pm2-gui Settings → Startup',
    '# Task Scheduler command: sh ' + appDir + '/synology-start.sh',
    '',
    'APP_DIR=' + shellQuote(appDir),
    'USER_HOME=' + shellQuote(userHome),
    '',
    'export HOME="$USER_HOME"',
    'export PATH="$HOME/.npm-global/bin:/usr/local/bin:/var/packages/Node.js_v20/target/usr/local/bin:/var/packages/Node.js_v18/target/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:$PATH"',
    '',
    'LOG="$APP_DIR/pm2-gui.log"',
    '',
    '{',
    '  echo "=============================================================="',
    '  echo "start-pm2-gui: launch attempt"',
    '  echo "HOME=$HOME"',
    '  echo "PATH=$PATH"',
    '',
    '  cd "$APP_DIR" || { echo "ERROR: cannot cd to $APP_DIR"; exit 1; }',
    '',
    '  NODE_BIN="$(command -v node || true)"',
    '  if [ -z "$NODE_BIN" ]; then',
    '    echo "ERROR: node not found on PATH"',
    '    exit 1',
    '  fi',
    '  echo "using node: $NODE_BIN ($("$NODE_BIN" --version 2>/dev/null))"',
    '',
    '  PORT=8088',
    '  if command -v ss >/dev/null 2>&1; then',
    '    if ss -ltn 2>/dev/null | grep -q ":${PORT} "; then',
    '      echo "SKIP: port $PORT already in use"',
    '      exit 0',
    '    fi',
    '  elif command -v netstat >/dev/null 2>&1; then',
    '    if netstat -ltn 2>/dev/null | grep -q ":${PORT} "; then',
    '      echo "SKIP: port $PORT already in use"',
    '      exit 0',
    '    fi',
    '  fi',
    '',
    '  if command -v pm2 >/dev/null 2>&1; then',
    '    if pm2 describe pm2-gui >/dev/null 2>&1; then',
    '      echo "WARN: removing pm2-gui from PM2"',
    '      pm2 delete pm2-gui >/dev/null 2>&1 || true',
    '      pm2 save >/dev/null 2>&1 || true',
    '    fi',
    '  fi',
    '',
    '  echo "launching: node pm2-gui.js start"',
    '  setsid "$NODE_BIN" pm2-gui.js start >> "$LOG" 2>&1 &',
    '  echo "launched pid $! at $(date 2>/dev/null)"',
    '} >> "$LOG" 2>&1',
    ''
  ].join('\n')
}

function shellQuote (value) {
  return "'" + String(value).replace(/'/g, "'\\''") + "'"
}

function ensureStartScript () {
  var scriptPath = getStartScriptPath()
  fs.writeFileSync(scriptPath, buildStartScript(), { mode: 0o755 })
  try {
    fs.chmodSync(scriptPath, 0o755)
  } catch (err) {}
  return scriptPath
}

function getManualInstructions () {
  var scriptPath = getStartScriptPath()
  var user = os.userInfo().username
  return {
    title: 'Manual Synology Task Scheduler setup',
    steps: [
      'Open Control Panel → Task Scheduler',
      'Create → Triggered Task → User-defined script',
      'Task name: ' + TASK_NAME,
      'User: ' + user + ' (same user that runs PM2)',
      'Event: Boot-up',
      'Enable: checked',
      'Task Settings → User-defined script:',
      'sh ' + scriptPath
    ],
    command: 'sh ' + scriptPath
  }
}

function listSchedulerTasks (fn) {
  var synowebapi = which('synowebapi') || '/usr/syno/bin/synowebapi'
  if (!fs.existsSync(synowebapi)) {
    return fn(new Error('synowebapi not found'))
  }

  execFile(synowebapi, [
    '--exec-fastwebapi',
    'api=SYNO.Core.TaskScheduler',
    'method=list',
    'version=3'
  ], { timeout: 15000 }, function (err, stdout) {
    if (err) {
      return fn(err)
    }
    try {
      var json = JSON.parse(stdout)
      if (!json.success) {
        return fn(new Error((json.error && json.error.code) ? 'TaskScheduler list failed: ' + json.error.code : 'TaskScheduler list failed'))
      }
      fn(null, (json.data && json.data.tasks) || [])
    } catch (parseErr) {
      fn(parseErr)
    }
  })
}

function findExistingTask (tasks) {
  return (tasks || []).find(function (task) {
    return task && task.name === TASK_NAME
  }) || null
}

function createViaSynowebapi (scriptPath, owner, fn) {
  var synowebapi = which('synowebapi') || '/usr/syno/bin/synowebapi'
  if (!fs.existsSync(synowebapi)) {
    return fn(new Error('synowebapi not found on this system'))
  }

  var schedule = JSON.stringify({
    date_type: 3,
    week_day: '0,1,2,3,4,5,6',
    hour: 0,
    minute: 0,
    repeat_hour: 0,
    repeat_min: 0,
    last_work_hour: 0
  })
  var script = 'sh ' + scriptPath

  // Prefer Script Create API (DSM 7).
  execFile(synowebapi, [
    '--exec-fastwebapi',
    'api=SYNO.Core.TaskScheduler.Script',
    'method=Create',
    'version=2',
    'task_name=' + TASK_NAME,
    'script=' + script,
    'schedule=' + schedule,
    'enabled=true'
  ], { timeout: 20000 }, function (err, stdout, stderr) {
    if (!err) {
      try {
        var json = JSON.parse(stdout)
        if (json.success) {
          return fn(null, {
            method: 'synowebapi.Script.Create',
            taskId: json.data && (json.data.task_id || json.data.id),
            raw: json
          })
        }
      } catch (parseErr) {}
    }

    // Fallback: older TaskScheduler create shape.
    execFile(synowebapi, [
      '--exec-fastwebapi',
      'api=SYNO.Core.TaskScheduler',
      'method=create',
      'version=4',
      'name=' + TASK_NAME,
      'owner=' + owner,
      'enable=true',
      'type=script',
      'schedule=' + schedule,
      'extra=' + JSON.stringify({ script: script })
    ], { timeout: 20000 }, function (err2, stdout2) {
      if (err2) {
        return fn(new Error(
          'Could not create Task Scheduler entry automatically. ' +
          'DSM usually requires an administrator session for this API. ' +
          (stderr || err2.message || '')
        ))
      }
      try {
        var json2 = JSON.parse(stdout2)
        if (json2.success) {
          return fn(null, {
            method: 'synowebapi.TaskScheduler.create',
            taskId: json2.data && (json2.data.id || json2.data.task_id),
            raw: json2
          })
        }
        return fn(new Error('Task Scheduler create returned success=false'))
      } catch (parseErr2) {
        return fn(parseErr2)
      }
    })
  })
}

function installUserCrontab (scriptPath, fn) {
  var marker = '# pm2-gui-boot'
  var line = '@reboot /bin/sh ' + scriptPath + ' ' + marker

  execFile('crontab', ['-l'], { timeout: 5000 }, function (err, stdout) {
    var existing = (!err && stdout) ? stdout : ''
    if (existing.indexOf(marker) >= 0) {
      return fn(null, { method: 'crontab', status: 'already_installed' })
    }

    var next = existing.replace(/\s*$/, '')
    if (next) next += '\n'
    next += line + '\n'

    var child = execFile('crontab', ['-'], { timeout: 5000 }, function (err2) {
      if (err2) {
        return fn(err2)
      }
      fn(null, { method: 'crontab', status: 'installed' })
    })
    child.stdin.write(next)
    child.stdin.end()
  })
}

function getStatus (fn) {
  var synology = isSynology()
  var scriptPath = getStartScriptPath()
  var scriptExists = fs.existsSync(scriptPath)
  var owner = os.userInfo().username
  var status = {
    synology: synology,
    platform: process.platform,
    appDir: detectAppDir(),
    userHome: detectUserHome(),
    owner: owner,
    scriptPath: scriptPath,
    scriptExists: scriptExists,
    command: 'sh ' + scriptPath,
    taskName: TASK_NAME,
    canAutoCreate: synology && fs.existsSync('/usr/syno/bin/synowebapi'),
    existingTask: null,
    bootEnabled: !!db.getSetting('boot_task_enabled', false),
    lastMethod: db.getSetting('boot_task_method', ''),
    instructions: getManualInstructions()
  }

  if (!synology) {
    return fn(null, status)
  }

  listSchedulerTasks(function (err, tasks) {
    if (!err) {
      status.existingTask = findExistingTask(tasks)
    }
    fn(null, status)
  })
}

function setupBootTask (options, fn) {
  if (typeof options === 'function') {
    fn = options
    options = {}
  }
  options = options || {}

  var scriptPath = ensureStartScript()
  var owner = os.userInfo().username
  var result = {
    scriptPath: scriptPath,
    command: 'sh ' + scriptPath,
    methods: [],
    instructions: getManualInstructions()
  }

  function finish (ok, method) {
    db.setSetting('boot_task_enabled', !!ok)
    if (method) db.setSetting('boot_task_method', method)
    result.ok = !!ok
    result.method = method || null
    fn(null, result)
  }

  if (!isSynology()) {
    // Non-Synology: still write script + optional crontab.
    if (options.preferCrontab !== false) {
      return installUserCrontab(scriptPath, function (err, info) {
        if (err) {
          result.error = err.message
          result.methods.push({ method: 'crontab', ok: false, error: err.message })
          return finish(false)
        }
        result.methods.push({ method: 'crontab', ok: true, info: info })
        finish(true, 'crontab')
      })
    }
    result.note = 'Not running on Synology. Start script was written; use the manual instructions or a system service.'
    return finish(false)
  }

  createViaSynowebapi(scriptPath, owner, function (err, info) {
    if (!err && info) {
      result.methods.push({ method: info.method, ok: true, info: info })
      return finish(true, info.method)
    }

    result.methods.push({
      method: 'synowebapi',
      ok: false,
      error: err ? err.message : 'unknown error'
    })

    // Fallback: user crontab @reboot (no admin UI needed).
    installUserCrontab(scriptPath, function (cronErr, cronInfo) {
      if (cronErr) {
        result.methods.push({ method: 'crontab', ok: false, error: cronErr.message })
        result.error = (err && err.message) || cronErr.message
        result.note = 'Automatic Task Scheduler creation failed (often needs DSM admin privileges). Use the manual steps below, or run this app as a user that can call synowebapi.'
        return finish(false)
      }
      result.methods.push({ method: 'crontab', ok: true, info: cronInfo })
      result.note = 'DSM Task Scheduler API was unavailable, so a user crontab @reboot entry was installed instead.'
      finish(true, 'crontab')
    })
  })
}

module.exports = {
  TASK_NAME: TASK_NAME,
  isSynology: isSynology,
  getStatus: getStatus,
  setupBootTask: setupBootTask,
  ensureStartScript: ensureStartScript,
  getManualInstructions: getManualInstructions
}
